"use client";
import {useEffect,useMemo,useState} from "react";
import {Bike,Clock3,MapPin,MessageCircle,Minus,Plus,Search,ShoppingBag,X} from "lucide-react";
import {categories,menuItems,MenuItem} from "@/data/menu";
type CartItem=MenuItem&{quantity:number};
const money=new Intl.NumberFormat("pt-BR",{style:"currency",currency:"BRL"}); const WHATSAPP="5582996451844";
export default function Home(){const[category,setCategory]=useState("Todos");const[query,setQuery]=useState("");const[cart,setCart]=useState<CartItem[]>([]);const[openCart,setOpenCart]=useState(false);useEffect(()=>{const s=localStorage.getItem("vovo-marly-cart");if(s){try{setCart(JSON.parse(s))}catch{}}},[]);useEffect(()=>{localStorage.setItem("vovo-marly-cart",JSON.stringify(cart))},[cart]);const filtered=useMemo(()=>{const q=query.trim().toLowerCase();return menuItems.filter(i=>(category==="Todos"||i.category===category)&&(!q||`${i.name} ${i.description} ${i.category}`.toLowerCase().includes(q)))},[category,query]);const count=cart.reduce((a,b)=>a+b.quantity,0);const subtotal=cart.reduce((a,b)=>a+b.price*b.quantity,0);function add(i:MenuItem){setCart(c=>{const f=c.find(x=>x.id===i.id);return f?c.map(x=>x.id===i.id?{...x,quantity:x.quantity+1}:x):[...c,{...i,quantity:1}]})}function qty(id:string,d:number){setCart(c=>c.map(x=>x.id===id?{...x,quantity:x.quantity+d}:x).filter(x=>x.quantity>0))}const orderLink=useMemo(()=>{const t=["Olá! Quero fazer um pedido no Tempero da Vovó Marly:","",...cart.map(i=>`• ${i.quantity}x ${i.name} — ${money.format(i.price*i.quantity)}`),"",`Subtotal: ${money.format(subtotal)}`,"","Pode me passar os próximos passos?"].join("\n");return `https://wa.me/${WHATSAPP}?text=${encodeURIComponent(t)}`},[cart,subtotal]);return <main>
<header className="topbar"><div className="container nav"><a className="brand" href="#"><img src="/brand/logo.png" alt="Tempero da Vovó Marly"/><div><strong>Tempero da Vovó Marly</strong><span>Sabor de casa, carinho de vó.</span></div></a><div className="nav-actions"><a className="wa-top" href={`https://wa.me/${WHATSAPP}`} target="_blank"><MessageCircle size={18}/>WhatsApp</a><button className="cart-top" onClick={()=>setOpenCart(true)}><ShoppingBag size={18}/>Carrinho{count>0&&<b>{count}</b>}</button></div></div></header>
<section className="hero-wrap"><div className="container hero"><div className="hero-copy"><span className="tag">Cardápio online</span><h1>Comida de verdade, com sabor de casa.</h1><p>Escolha seu prato, monte seu pedido e fale com a gente em poucos cliques.</p><div className="hero-info"><span><Clock3 size={17}/>Aberto hoje até 16h</span><span><Bike size={17}/>Delivery e retirada</span><span><MapPin size={17}/>Atendimento local</span></div><div className="hero-buttons"><a href="#cardapio" className="btn-orange">Ver cardápio</a><a href={`https://wa.me/${WHATSAPP}`} target="_blank" className="btn-ghost">Pedir no WhatsApp</a></div></div><div className="hero-visual"><div className="sun"></div><img src="/brand/mascote.png" alt="Vovó Marly"/><div className="hero-stamp"><small>ALMOÇO</small><strong>a partir de</strong><b>R$ 16,00</b></div></div></div></section>
<section className="container trust-strip"><div><span>01</span><strong>Comida caseira</strong><p>Tempero marcante e aquele jeitinho de casa.</p></div><div><span>02</span><strong>Pedido rápido</strong><p>Escolha no site e finalize pelo WhatsApp.</p></div><div><span>03</span><strong>Feito com carinho</strong><p>Da cozinha da Vovó Marly direto pra sua mesa.</p></div></section>
<section className="promo-section container"><div className="section-head"><div><span className="eyebrow">Hoje tem</span><h2>Cardápio com cara de comida boa.</h2></div><p>Alguns destaques da identidade que já fazem parte da marca.</p></div><div className="promo-grid"><article className="promo-large"><img src="/brand/cardapio-almoco.jpeg" alt="Cardápio do almoço"/></article><article className="promo-small"><img src="/brand/cardapio-dia.jpeg" alt="Cardápio do dia"/></article><article className="promo-small"><img src="/brand/churrasco.jpeg" alt="Churrasco na brasa"/></article></div></section>
<section className="container menu-section" id="cardapio"><div className="section-head"><div><span className="eyebrow">Peça do seu jeito</span><h2>Escolha o que vai pra mesa.</h2></div><p>{filtered.length} opções disponíveis</p></div><div className="search"><Search size={20}/><input value={query} onChange={e=>setQuery(e.target.value)} placeholder="Buscar prato, acompanhamento, sobremesa..."/></div><div className="categories">{categories.map(c=><button key={c} onClick={()=>setCategory(c)} className={category===c?"active":""}>{c}</button>)}</div><div className="menu-grid">{filtered.map(item=><article className="food-card" key={item.id}><div className="food-photo"><span>{item.emoji}</span>{item.tag&&<b>{item.tag}</b>}</div><div className="food-body"><small>{item.category}</small><h3>{item.name}</h3><p>{item.description}</p><div className="food-bottom"><div>{item.oldPrice&&<del>{money.format(item.oldPrice)}</del>}<strong>{money.format(item.price)}</strong></div><button onClick={()=>add(item)}><Plus size={19}/></button></div></div></article>)}</div></section>
<section className="container callout"><div><span className="eyebrow light">Tempero da Vovó Marly</span><h2>Sabor de casa, carinho de vó.</h2><p>Monte seu pedido e deixe o resto com a gente.</p></div><a href={`https://wa.me/${WHATSAPP}`} target="_blank">Fazer pedido</a></section>
<footer><div className="container footer-inner"><div className="footer-brand"><img src="/brand/logo.png" alt=""/><div><strong>Tempero da Vovó Marly</strong><span>Delivery: (82) 9 9645-1844</span></div></div><span>Feito com carinho pra você.</span></div></footer>
{openCart&&<><button className="overlay" onClick={()=>setOpenCart(false)}/><aside className="cart-panel"><div className="cart-head"><div><small>SEU PEDIDO</small><h2>Carrinho</h2></div><button onClick={()=>setOpenCart(false)}><X size={22}/></button></div><div className="cart-list">{cart.length===0?<div className="empty"><ShoppingBag size={42}/><h3>Seu carrinho está vazio</h3><p>Adicione seus pratos favoritos.</p></div>:cart.map(item=><div className="cart-item" key={item.id}><div className="cart-emoji">{item.emoji}</div><div className="cart-info"><strong>{item.name}</strong><span>{money.format(item.price)}</span><div className="counter"><button onClick={()=>qty(item.id,-1)}><Minus size={14}/></button><b>{item.quantity}</b><button onClick={()=>qty(item.id,1)}><Plus size={14}/></button></div></div><strong>{money.format(item.price*item.quantity)}</strong></div>)}</div><div className="cart-footer"><div><span>Subtotal</span><strong>{money.format(subtotal)}</strong></div><p>Entrega e pagamento são combinados no atendimento.</p><a className={cart.length?"":"disabled"} href={cart.length?orderLink:"#"} target="_blank">Enviar pedido no WhatsApp</a></div></aside></>}
{count>0&&!openCart&&<button className="mobile-cart" onClick={()=>setOpenCart(true)}><span><ShoppingBag size={18}/>{count} {count===1?"item":"itens"}</span><strong>{money.format(subtotal)}</strong></button>}
</main>}
