"use client";
import {useEffect,useMemo,useState} from "react";
import {Plus,Search,ShoppingBag} from "lucide-react";
import {collection,getDocs,query,where} from "firebase/firestore";
import {db} from "@/lib/firebase"; import type {Product} from "@/lib/types"; import {fallbackProducts} from "@/data/fallback";
const money=new Intl.NumberFormat("pt-BR",{style:"currency",currency:"BRL"}); const STORE="tempero-da-vovo-marly";
export default function Home(){const[products,setProducts]=useState<Product[]>(fallbackProducts);const[q,setQ]=useState("");const[cat,setCat]=useState("Todos");
useEffect(()=>{(async()=>{try{const s=await getDocs(query(collection(db,"products"),where("storeId","==",STORE),where("active","==",true)));const r=s.docs.map(d=>({id:d.id,...d.data()} as Product));if(r.length)setProducts(r.sort((a,b)=>(a.order||0)-(b.order||0)))}catch{}})()},[]);
const cats=useMemo(()=>["Todos",...Array.from(new Set(products.map(p=>p.categoryName).filter(Boolean)))],[products]);const list=products.filter(p=>(cat==="Todos"||p.categoryName===cat)&&(`${p.name} ${p.description}`.toLowerCase().includes(q.toLowerCase())));const daily=products.filter(p=>p.dailySpecial).slice(0,3);
return <main><header className="top"><div className="wrap nav"><div className="brand"><img src="/brand/logo-round.png"/><div><b>Tempero da Vovó Marly</b><span>Sabor de casa, carinho de vó.</span></div></div><div className="navlinks"><a href="/admin">Admin</a><a className="pill green" href="https://wa.me/5582996451844">WhatsApp</a></div></div></header>
<section className="hero wrap"><div className="heroCopy"><span className="eyebrow">Cardápio online</span><h1>Comida boa, caseira e feita com carinho.</h1><p>Escolha seu prato, monte seu pedido e fale com a equipe em poucos cliques.</p><a className="cta" href="#cardapio">Ver cardápio</a></div><div className="heroCard"><img src="/brand/logo-round.png"/><strong>Tempero da Vovó Marly</strong><span>Sabor de casa, carinho de vó.</span><div className="priceBox">ALMOÇO <b>a partir de R$ 16,00</b></div></div></section>
{daily.length>0&&<section className="wrap section"><div className="heading"><div><span className="eyebrow">Hoje tem</span><h2>Cardápio do dia</h2></div></div><div className="dailyGrid">{daily.map(p=><article key={p.id}><div className="imgBox">{p.imageUrl?<img src={p.imageUrl}/>:"🍽️"}</div><div><h3>{p.name}</h3><p>{p.description}</p><b>{money.format(p.promotionalPrice||p.price)}</b></div></article>)}</div></section>}
<section className="wrap section" id="cardapio"><div className="heading"><div><span className="eyebrow">Peça do seu jeito</span><h2>Escolha o que vai para a mesa.</h2></div><span>{list.length} opções</span></div><div className="search"><Search size={18}/><input value={q} onChange={e=>setQ(e.target.value)} placeholder="Buscar prato..."/></div><div className="cats">{cats.map(c=><button className={c===cat?"active":""} onClick={()=>setCat(c)} key={c}>{c}</button>)}</div><div className="grid">{list.map(p=><article className="food" key={p.id}><div className="foodImg">{p.imageUrl?<img src={p.imageUrl}/>:"🍽️"}{p.featured&&<span>Destaque</span>}</div><div className="foodBody"><small>{p.categoryName}</small><h3>{p.name}</h3><p>{p.description}</p><div><b>{money.format(p.promotionalPrice||p.price)}</b><button><Plus size={18}/></button></div></div></article>)}</div></section>
<section className="wrap poster"><img src="/brand/poster-dia.jpg"/></section><footer><div className="wrap">Tempero da Vovó Marly • Delivery (82) 9 9645-1844</div></footer></main>}
