"use client";
import {FormEvent,useEffect,useState} from "react"; import {Plus,Trash2,Pencil,LogOut,Save} from "lucide-react";
import {onAuthStateChanged,signInWithEmailAndPassword,signOut,User} from "firebase/auth";
import {addDoc,collection,deleteDoc,doc,getDoc,getDocs,query,updateDoc,where} from "firebase/firestore";
import {auth,db} from "@/lib/firebase"; import type {Product,Category} from "@/lib/types";
const STORE="tempero-da-vovo-marly";const money=new Intl.NumberFormat("pt-BR",{style:"currency",currency:"BRL"});
const empty={name:"",description:"",categoryId:"",categoryName:"",price:0,promotionalPrice:null as number|null,imageUrl:"",active:true,featured:false,dailySpecial:false,order:0};
export default function Admin(){const[user,setUser]=useState<User|null>(null);const[ok,setOk]=useState(false);const[loading,setLoading]=useState(true);const[email,setEmail]=useState("");const[password,setPassword]=useState("");const[err,setErr]=useState("");const[products,setProducts]=useState<Product[]>([]);const[cats,setCats]=useState<Category[]>([]);const[form,setForm]=useState(empty);const[editing,setEditing]=useState<string|null>(null);const[show,setShow]=useState(false);const[newCat,setNewCat]=useState("");
async function load(){const[p,c]=await Promise.all([getDocs(query(collection(db,"products"),where("storeId","==",STORE))),getDocs(query(collection(db,"categories"),where("storeId","==",STORE)))]);setProducts(p.docs.map(d=>({id:d.id,...d.data()} as Product)));setCats(c.docs.map(d=>({id:d.id,...d.data()} as Category)))}
useEffect(()=>onAuthStateChanged(auth,async u=>{setUser(u);if(!u){setOk(false);setLoading(false);return}try{const s=await getDoc(doc(db,"users",u.uid));const d=s.data();const allowed=!!d&&d.active===true&&d.role==="admin"&&d.storeId===STORE;setOk(allowed);if(allowed)await load()}finally{setLoading(false)}}),[]);
async function login(e:FormEvent){e.preventDefault();setErr("");try{await signInWithEmailAndPassword(auth,email.trim(),password)}catch{setErr("E-mail ou senha inválidos.")}}
async function saveProduct(e:FormEvent){e.preventDefault();const c=cats.find(x=>x.id===form.categoryId);const payload={storeId:STORE,...form,categoryName:c?.name||"Sem categoria",price:Number(form.price),promotionalPrice:form.promotionalPrice?Number(form.promotionalPrice):null};if(editing)await updateDoc(doc(db,"products",editing),payload);else await addDoc(collection(db,"products"),payload);setShow(false);setEditing(null);setForm(empty);await load()}
function edit(p:Product){setEditing(p.id);setForm({name:p.name,description:p.description,categoryId:p.categoryId||"",categoryName:p.categoryName||"",price:p.price,promotionalPrice:p.promotionalPrice??null,imageUrl:p.imageUrl||"",active:p.active,featured:p.featured,dailySpecial:p.dailySpecial,order:p.order||0});setShow(true)}
async function remove(id:string){if(confirm("Excluir produto?")){await deleteDoc(doc(db,"products",id));await load()}}
async function addCategory(){if(!newCat.trim())return;await addDoc(collection(db,"categories"),{storeId:STORE,name:newCat.trim(),active:true,order:cats.length+1});setNewCat("");await load()}
if(loading)return <div className="center">Carregando...</div>;if(!user||!ok)return <main className="login"><form onSubmit={login}><img src="/brand/logo-round.png"/><span>ÁREA ADMINISTRATIVA</span><h1>Entrar no painel</h1><input type="email" placeholder="E-mail" value={email} onChange={e=>setEmail(e.target.value)} required/><input type="password" placeholder="Senha" value={password} onChange={e=>setPassword(e.target.value)} required/>{err&&<div className="error">{err}</div>}<button>Entrar</button><a href="/">Voltar ao cardápio</a></form></main>;
return <main className="admin"><aside><div className="aBrand"><img src="/brand/logo-round.png"/><div><b>Vovó Marly</b><span>Administração</span></div></div><nav><a href="#produtos">Produtos</a><a href="#categorias">Categorias</a></nav><button className="logout" onClick={()=>signOut(auth)}><LogOut size={16}/> Sair</button></aside><section><header><div><span>PAINEL</span><h1>Administração</h1></div><a href="/" target="_blank">Ver site</a></header><div className="stats"><article><span>Produtos</span><b>{products.length}</b></article><article><span>Ativos</span><b>{products.filter(p=>p.active).length}</b></article><article><span>Cardápio do dia</span><b>{products.filter(p=>p.dailySpecial).length}</b></article><article><span>Categorias</span><b>{cats.length}</b></article></div>
<div className="panel" id="produtos"><div className="panelHead"><div><span>CATÁLOGO</span><h2>Produtos</h2></div><button onClick={()=>{setEditing(null);setForm({...empty,order:products.length+1});setShow(true)}}><Plus size={16}/> Novo produto</button></div><div className="rows">{products.map(p=><div className="row" key={p.id}><div className="thumb">{p.imageUrl?<img src={p.imageUrl}/>:"🍽️"}</div><div><b>{p.name}</b><span>{p.categoryName}</span></div><strong>{money.format(p.promotionalPrice||p.price)}</strong><div className="acts"><button onClick={()=>edit(p)}><Pencil size={15}/></button><button onClick={()=>remove(p.id)}><Trash2 size={15}/></button></div></div>)}{!products.length&&<p>Nenhum produto cadastrado.</p>}</div></div>
<div className="panel" id="categorias"><div className="panelHead"><div><span>ORGANIZAÇÃO</span><h2>Categorias</h2></div></div><div className="catAdd"><input value={newCat} onChange={e=>setNewCat(e.target.value)} placeholder="Nova categoria"/><button onClick={addCategory}><Plus size={16}/> Adicionar</button></div><div className="catList">{cats.map(c=><div key={c.id}><b>{c.name}</b><span>Ordem {c.order}</span></div>)}</div></div></section>
{show&&<><button className="backdrop" onClick={()=>setShow(false)}/><div className="modal"><div className="mHead"><div><span>PRODUTO</span><h2>{editing?"Editar":"Novo"} produto</h2></div><button onClick={()=>setShow(false)}>×</button></div><form onSubmit={saveProduct}><label>Nome<input value={form.name} onChange={e=>setForm({...form,name:e.target.value})} required/></label><label>Descrição<textarea rows={3} value={form.description} onChange={e=>setForm({...form,description:e.target.value})}/></label><label>Categoria<select value={form.categoryId} onChange={e=>setForm({...form,categoryId:e.target.value})}><option value="">Sem categoria</option>{cats.map(c=><option value={c.id} key={c.id}>{c.name}</option>)}</select></label><div className="two"><label>Preço<input type="number" step="0.01" value={form.price} onChange={e=>setForm({...form,price:Number(e.target.value)})}/></label><label>Promocional<input type="number" step="0.01" value={form.promotionalPrice??""} onChange={e=>setForm({...form,promotionalPrice:e.target.value?Number(e.target.value):null})}/></label></div><label>URL da imagem<input type="url" value={form.imageUrl} onChange={e=>setForm({...form,imageUrl:e.target.value})} placeholder="https://..."/></label><div className="checks"><label><input type="checkbox" checked={form.active} onChange={e=>setForm({...form,active:e.target.checked})}/> Ativo</label><label><input type="checkbox" checked={form.featured} onChange={e=>setForm({...form,featured:e.target.checked})}/> Destaque</label><label><input type="checkbox" checked={form.dailySpecial} onChange={e=>setForm({...form,dailySpecial:e.target.checked})}/> Cardápio do dia</label></div><button className="save"><Save size={16}/> Salvar</button></form></div></>}</main>}
